---
title: "Modelos de Representación del Conocimiento"
output: html_document
---

<br/>


### Información General

- Profesor: [Víctor Peinado](mailto:v.peinado@filol.ucm.es)

- [Ficha de la asignatura: curso 2014-3015](ficha-RepresentacionConocimiento.pdf)

- Horario: 1er semestre, JV de 12h30 a 14h30

- Tutorías: JV, de 15h00 a 18h00

<br/>


### Materiales

1. Introducción a la Representación del Conocimiento

    - [Resumen](IntroRC.pdf)

    - Capítulo 1 de Brachman, R.; Levesque, H. [*Knowledge Representation and Reasoning*](http://rair.cogsci.rpi.edu/pai/library/brachmanbook7-17-03.pdf). Morgan Kaufmann. 2004.

    - [Presentaciones de Levesque del libro *Knowledge Representation and Reasoning*](http://www.cs.toronto.edu/~hector/PublicKRSlides.pdf)

    - [Videolectures: Knowledge Representation and Reasoning](http://videolectures.net/ssll09_pagnucco_krr/)


2. Teoría de conjuntos, relaciones y funciones

    - [Teoría de Conjuntos](Conjuntos.pdf)
    
    - [Relaciones](Relaciones.pdf)

    - [Funciones](Funciones.pdf)


3. Lógica y Sistemas Formales

    - [Introdución a la Lógica y los Sistemas Formales](IntroLogica.pdf)

    - [Lógica Proposicional](LogicaProposicional.pdf)

    - [Lógica de Predicados](LogicaPredicados.pdf)


4. Programación en Prolog

    - [Introducción a Prolog: hechos, reglas, consultas](Prolog-Hechos-Reglas-Consultas.pdf) 

    - [Prolog: unificación y recursión](Prolog-Unificacion-Recursion.pdf) 

    - [Prolog: Listas](Prolog-Listas.pdf) 

    - [Prolog: Operaciones aritméticas](Prolog-Aritmetica.pdf) 

    - [Prolog: Más listas](Prolog-Listas2.pdf) 
    
    
5. Representación del Conocimiento Lingüístico

    - Farfar & Langendown. "A linguistic ontology for the semantic web". 2003.
    - Shi & Mihalcea. "Putting Pieces Together: Combining FrameNet, VerbNet and WordNet for Robust Semantic Parsing". 2005.
    - Chiarcos *et al.* "Towards Open Data for Linguistics: Linguistic Linked Data". 2013.
    - [Linguistic Linked Open Data cloud](http://linguistics.okfn.org/resources/llod/)
    
    
*Última modificación: 22/01/2015*

