---
title: "Programación para el Procesamiento del Lenguaje Natural"
output: html_document
---

<br/>

### Información General

- Profesor: [Víctor Peinado](mailto:v.peinado@filol.ucm.es)

- [Ficha de la asignatura: curso 2014-3015](ficha-ProgramacionPLN.pdf)

- Horario: 1er semestre, JV de 10h30 a 12h30

- Tutorías: JV, de 15h00 a 18h00


<br/>


### Materiales

1. **Introducción al Procesamiento del Lenguaje Natural**

    - [Resumen](IntroPLN.pdf)

    - Lectura: [What Can Computational Linguistics Do For You?](http://clic.cimec.unitn.it/brian/compLingITC/whatGoodCL.html)


2. **Herramientas de Unix para procesamiento de texto**

    - [Conexiones a través de SSH](conexiones-SSH.pdf)

    - Lectura: [Basic concepts of computers: hardware and software](http://clic.cimec.unitn.it/brian/compLingITC/computers.html)
    
    - [Shell de Unix: gestión de ficheros y directorios](ShellUnix.pdf)
    
    - [Shell de Unix: procesamiento de texto](ShellUnix-proc-text.pdf)
    
    - [Expresiones regulares](Regexes.pdf)



3. **Procesamiento del Lenguaje Natural en Python**

    - [Introducción a Python: variables y estructura de datos](http://nbviewer.ipython.org/github/vitojph/2014progpln/blob/master/1-Intro-Python.ipynb)
    
    - [Introducción a Python: control de flujo](http://nbviewer.ipython.org/github/vitojph/2014progpln/blob/master/2-Python-control-fujo.ipynb)
    
    - [Introducción a Python: bucles](http://nbviewer.ipython.org/github/vitojph/2014progpln/blob/master/3-Python-bucles.ipynb)
    
    - [Introducción a Python: funciones](http://nbviewer.ipython.org/github/vitojph/2014progpln/blob/master/4-Python-Funciones.ipynb)
    
    
4. **Herramientas de PLN en Python**    
    
    - [NLTK: Acceso a corpus de texto y recursos léxicos](http://nbviewer.ipython.org/github/vitojph/2014progpln/blob/master/5-nltk-corpus.ipynb)
    - [NLTK: Etiquetado morfológico](http://nbviewer.ipython.org/github/vitojph/2014progpln/blob/master/6-nltk-pos.ipynb)
    - [NLTK: Análisis sintáctico](http://nbviewer.ipython.org/github/vitojph/2014progpln/blob/master/7-nltk-analyzers.ipynb)
    - [`pattern.en` y `pattern.es`: procesamiento del lenguaje en inglés y español](http://nbviewer.ipython.org/github/vitojph/2014progpln/blob/master/8-pattern-en-es.ipynb)
    - [`pattern.web`: accediendo a buscadores, Wikipedia y Twitter](http://nbviewer.ipython.org/github/vitojph/2014progpln/blob/master/9-pattern-web.ipynb)
    - [TextBlob: Herramientas de procesamiento de texto](http://nbviewer.ipython.org/github/vitojph/2014progpln/blob/master/10-textblob.ipynb)
    
*Última modificación: 22/01/2015*
